AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'xambda

  Sample SAM Template for xambda

  '
Globals:
  Function:
    Timeout: 60
Resources:
  XambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://BUCKET/HASH
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        Xambda:
          Type: Api
          Properties:
            Path: /hello
            Method: get
Outputs:
  XambdaApi:
    Description: API Gateway endpoint URL for Prod stage for Xambda function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  XambdaFunction:
    Description: Xambda Lambda Function ARN
    Value:
      Fn::GetAtt:
      - XambdaFunction
      - Arn
  XambdaFunctionIamRole:
    Description: Implicit IAM Role created for Xambda function
    Value:
      Fn::GetAtt:
      - XambdaFunctionRole
      - Arn
