AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  xambda

  Sample SAM Template for xambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  XambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: xambda/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        Xambda:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  XambdaApi:
    Description: "API Gateway endpoint URL for Prod stage for Xambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  XambdaFunction:
    Description: "Xambda Lambda Function ARN"
    Value: !GetAtt XambdaFunction.Arn
  XambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Xambda function"
    Value: !GetAtt XambdaFunctionRole.Arn
